/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-dim": "#e8e4da",
        "surface-bright": "#fdfcf8",
        "surface": "#f6f3eb",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f1ece0",
        "surface-container": "#ece6d9",
        "surface-container-high": "#e6e0d2",
        "surface-container-highest": "#dfd7c7",
        "surface-variant": "#e8e3d5",
        "on-surface": "#131c18",
        "on-surface-variant": "#36443e",
        "primary": "#182822",
        "primary-container": "#121e1a",
        "on-primary": "#fbf9f4",
        "secondary": "#a8653b",
        "secondary-container": "#a8653b",
        "on-secondary": "#ffffff",
        "tertiary": "#8b4e28",
        "outline": "#9e8a70",
        "outline-variant": "#d2b48c",
        "racing-dark": "#121e1a",
        "racing-green": "#182822",
        "saddle-cognac": "#a8653b",
        "saddle-tan": "#8b4e28",
        "antique-brass": "#c4a97d",
        "warm-cream": "#fbf9f4",
        "moss-tint": "#e3e8e1",
        "parchment": "#fbf9f3",
        "espresso": "#241e1b",
        "espresso-deep": "#191513",
        "cognac": "#8b5a3c",
        "ochre-gold": "#d79624",
        "gold-ochre": "#dda129",
        "warm-bone": "#f5f3ed",
        "hairline": "#e5dfd5",
      },
      fontFamily: {
        serif: ["Newsreader", "Georgia", "serif"],
        sans: ["'Hanken Grotesk'", "system-ui", "sans-serif"],
        "headline-md": ["Newsreader", "Georgia", "serif"],
        "body-sm": ["'Hanken Grotesk'", "system-ui", "sans-serif"],
        "display-xl": ["Newsreader", "Georgia", "serif"],
        "label-lg": ["'Hanken Grotesk'", "system-ui", "sans-serif"],
        "body-lg": ["'Hanken Grotesk'", "system-ui", "sans-serif"],
        "spec-numeral": ["'Hanken Grotesk'", "monospace"],
        "display-xl-mobile": ["Newsreader", "Georgia", "serif"],
        "body-md": ["'Hanken Grotesk'", "system-ui", "sans-serif"],
        "headline-lg-mobile": ["Newsreader", "Georgia", "serif"],
        "headline-lg": ["Newsreader", "Georgia", "serif"],
        "headline-sm": ["Newsreader", "Georgia", "serif"],
        "label-sm": ["'Hanken Grotesk'", "system-ui", "sans-serif"],
        "label-md": ["'Hanken Grotesk'", "system-ui", "sans-serif"],
      },
      fontSize: {
        "display-xl": ["56px", { lineHeight: "64px", letterSpacing: "-0.02em", fontWeight: "400" }],
        "display-xl-mobile": ["38px", { lineHeight: "44px", letterSpacing: "-0.015em", fontWeight: "400" }],
        "headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.015em", fontWeight: "400" }],
        "headline-lg-mobile": ["30px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "headline-md": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "headline-sm": ["22px", { lineHeight: "28px", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "18px", letterSpacing: "0.04em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.06em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.08em", fontWeight: "600" }],
        "spec-numeral": ["13px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
      },
      spacing: {
        "space-xl": "3rem",
        "space-lg": "1.75rem",
        "space-md": "1rem",
        "space-sm": "0.5rem",
        "space-xs": "0.25rem",
        "gutter": "1.5rem",
        "gutter-mobile": "0.75rem",
        "margin": "3.5rem",
        "margin-tablet": "2rem",
        "margin-mobile": "1.25rem",
      },
    },
  },
  plugins: [],
};
